### ISSUE TITLE
Adding ggordiplot ellipse to Ampvis2 ordination plot

### ISSUE THREAD

**Issue by afmbafmb** [jfq3/ggordiplots#4]
Hi John,

Thanks for developing ggordiplot. I would like to use the ordination plots from Ampvis2 package instead of building ordination plot from scratch. I was just wondering if it is possible to incorporate the ellipse function used in ggordiplot into the Ampvis2 plots. Here is an example workflow: 

``` r
library(ampvis2)
#> Loading required package: ggplot2

data("MiDAS")
MiDASsubset <- amp_subset_samples(MiDAS, Plant %in% c("Aalborg West", "Aalborg East"))
#> 590 samples and 5512 OTUs have been filtered 
#> Before: 658 samples and 14969 OTUs
#> After: 68 samples and 9457 OTUs
amp_ordinate(MiDASsubset, 
             type = "pcoa",
             distmeasure = "bray",
             sample_color_by = "Plant")
#> Calculating distance matrix...
#> Done.
#> Warning: Using both transformation AND a distance measure is not
#> recommended for distance-based ordination (nMDS/PCoA/DCA). If this is not
#> deliberate, consider transform = "none".
```

![](https://i.imgur.com/OY849uE.png)

<sup>Created on 2019-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks!

**Comment by jfq3** [comment]
Not easily. It is far easier to recreate the ordination with vegan functions and then plot with gg_ordipolot:

library(ade4)
library(vegan)
library(ggordiplots)
sam <- MiDASsubset$metadata
otu <- t(MiDASsubset$abund)
otu.hel <- decostand(otu, "hellinger") # By default, amp_ordinate makes this transformation.
d <- vegdist(otu.hel, "bray")
add <- !(is.euclid(d)) # Corrects for negative eigenvalues if necessary
pcoa <- cmdscale(d, k = nrow(otu)-1, eig = TRUE, add = add)
plt <- gg_ordiplot(pcoa, groups = sam$Plant, plot = FALSE)$plot
plt + theme_minimal() + labs(color = "Plant")

![image](https://user-images.githubusercontent.com/8404415/64703491-88ef6600-d47a-11e9-8762-faea756d09b7.png)

I did notice that the percent variation associated with the axes in your plot are incorrect.

**Comment by afmbafmb** [comment]
Thanks so much! I think I'll do it this way... I'm not so sure abt the percent variation though. Maybe it could be due to the Hellinger transformation.
