### ISSUE TITLE
Trouble installing package

### ISSUE THREAD

**Issue by elditria** [jfq3/ggordiplots#6]
Hi,
I'm having trouble installing ggordiplots in rstudio, i have ggplot2 and vegan installed but i keep getting the following errors:

install.packages("ggordiplots"): Warning in install.packages  package ‘ggordiplots’ is not available (for R version 3.6.2)

remotes::install_github("jfq3/ggordiplots"): 
Error: Failed to install 'ggordiplots' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’

Could you tell me how to install this package?
thanks

**Comment by jfq3** [comment]
Did you get a prompt like the following?
These packages have more recent versions available.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: digest (0.6.23 -> 0.6.24) [CRAN]

Enter one or more numbers, or an empty line to skip updates:

If so, try entering an empty line in response. If that fails, try removing the digest package manually first:
remove.packages("digest")

And then when prompted reinstall digest from source.
